on:
  pull_request:
    paths:
      - '**/*.ts'
      - .github/workflows/ci.yml
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        env:
          NODE_ENVIRONMENT: development
          # ^^ or we donâ€™t get dev-dependencies
      - run: npm test
  check-generated-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        env:
          NODE_ENVIRONMENT: development
      - run: npm run dist
      - run: git diff --exit-code
